### PR TITLE
add RTL Support to Enso/Main

### PR DESCRIPTION
**Pull request by YacoubBelaoura**
config/enso/themes.php
i added my github ver of bulma-rtl package for a fix.

### CODE REVIEW

**Comment by YacoubBelaoura** [comment]
refactor for v3

**Comment by aocneanu** [comment]
Hei @YacoubBelaoura ,

I was intending to do myself the conversion to v3 based on your initial PRs but if you're willing to do the work of migrating the code yoursleft Thank You (again!).

I'm really sorry that the timing was as it was...

**Comment by YacoubBelaoura** [comment]
thanks, don't worry about it.

i was following your work for updating to V3, and i really like this new idea, so refactoring will help me learn more.

now it will be easier for me to add support for tailwind css, that i was working on. so it will be easier to change the look completely with changing the package only. and a lot more features

**Comment by aocneanu** [comment]
Please consider adding the tailwind layout as a contribution too, that would be awesome.

During the process I can provide support on any issue related to this.

**Comment by YacoubBelaoura** [comment]
thanks, and yes of course i will contribute. that will help add more new looks and themes for enso.

and considering how tailwind works, what i want to do is add a  configuration page to tweak the looks as you like without needing to recompile  (so user don't need css knowledge, and that's whats most users like and ask about "themes + easy" )

**Pull request closed without merging**
