### PR TITLE
add Enso RTL support

### PR DESCRIPTION
**Pull request by YacoubBelaoura**
must add this line to **enso-core/resource/index.blade.php**
`<link id="enso_css" href="{{ mix('css/enso.css') }}" rel="stylesheet" type="text/css"/>`

### CODE REVIEW

**Comment by aocneanu** [comment]
;)

**Comment by aocneanu** [comment]
Make sure that you submit the PR to the core package..

**Comment by YacoubBelaoura** [comment]
Ok i will make a PR to the core package

**Comment by aocneanu** [comment]
Also, make sure that you only include in the PR the needed files.

**Comment by YacoubBelaoura** [comment]
the node package "bulma-rtl" is outdated, i submitted a fix but they aren't active
so i used my git repo 
`"bulma-rtl": "git+https://github.com/yacoubbelaoura/bulma-rtl.git#patch-1",`

**Comment by aocneanu** [comment]
Hi @YacoubBelaoura,

at each composer update enso [publishes](https://github.com/laravel-enso/Enso/blob/master/composer.json#L77) all the FE assets from its packages. This means that everything you PR'ed here will be overwritten. This is what I meant by
>Make sure that you submit the PR to the core package..

**Comment by YacoubBelaoura** [comment]
ah, ok thanks for clarification
i will submit the PR to the core package

**Pull request closed without merging**
