### PR TITLE
Client configurations outdated(vue.config.js) #372

### PR DESCRIPTION
**Pull request by robbykrlos**
- updated outdated package alias from @core to @ui according to Release notes from 4.4.0: 'the @core alias has been renamed to @ui, so update all usages ...'

### CODE REVIEW

**Comment by robbykrlos** [comment]
I have another pending PR that fixes the new CopyPlugin new format. Can someone accept this initial one?

**Comment by raftx24** [comment]
Hi @robbykrlos
I tried to test it but I got this error.
image

**Comment by robbykrlos** [comment]
I'll doublecheck this. Seems weird at first...

Thanks.

**Comment by robbykrlos** [comment]
@raftx24 -i've check my PR submission and apparently there is a problem with the versions we use for ``copy-webpack-plugin``

I used 5.1.2, and the code:

```js
new CopyPlugin({
                patterns: [{
                    from: '../resources/images',
                    to: 'images',
                    force: true,
                }],
            }),
``` 
is correct.

If I used your suggested code I get an error stating that ``patterns`` is missing.

I also found and read this:

https://github.com/webpack-contrib/copy-webpack-plugin/issues/455

So I guess in the end this change is not needed on your side. Sorry for this PR then.

**Pull request closed without merging**
