### PR TITLE
You can see what happens if not follow standards

### PR DESCRIPTION
**Pull request by nandordudas**
I recommend the airbnb rules too. I think You made a good work but, the codes quality is not reflected it.
I use Sublime and VSCode both, they have the eslint plugin and I open the file, wait for the plugins response and save the opened file, and open another file and wait and save and so on.
Necessary files only the package.json, .eslintrc.js and .editorconfig. I hope it can improve Your code.

### CODE REVIEW

**Comment by aocneanu** [comment]
Hi,

Your work looks great !

First, we are gonna change the title of the PR to something like airbnb style & eslint config upgrade :)

Second, I will need to review the files and then merge.

And third, after the merge I will split the files between the parent packages. Right now each package holds its related view components. All the core js assets (store, router, modules etc) are stored in the Core package, and the rest of the components belong to VueComponents.  The assets are supposed to be published after updates.

I will try my best to do this by the end of the week.

And indeed, your contribution improves the consistency and overall quality of the code.

Thank you ;)

**Comment by nandordudas** [comment]
Hi,
if You really want to merge files, rather I will make tests into a dev-* branch. Which pull request I sent to You its just a sample, I'm not tested!
I think the build js code is a bit large (15+MB) - [ex](https://youtu.be/_srJ7eHS3IM?t=29m58s). few route splitting.
I'm just giving You [tips](https://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository). I love Laravel and Vue (with sass and pug, Nuxt too).

And thank You for Your kind words!

**Comment by aocneanu** [comment]
Hi,

If you are willing to allocate more time on this you should choose a package to start with. The package with the most vue files is laravel-enso/vuecomponents, but I would suggest to start with something smaller, like menumanager, or logmanager. This way we can test easier.

In the following days I will include the config files in the Core package, and also publish them in the root of the project.

Cheers.

**Comment by aocneanu** [comment]
Hi Nandor,

I added the config in the main project. Also the core package is updated with eslint and airbnb, and also the localisation package.

Tommorow I will update some more.

I will close this pull request.

Cheers

**Comment by nandordudas** [comment]
Hi,

looks better. I hope the work will be easier for You.

Good work, bye

**Pull request closed without merging**
