### PR TITLE
 Add docker setup

### PR DESCRIPTION
**Pull request by bytebuddha**
This PR is more of a question. Would you consider adding a docker config to the enso library? I decided to make this a PR as opposed to an issue becuase then i can show you the current config im using for docker.

As written the user must run 

`docker-compose up --build -d` (Or just `docker-compose up`)

After it's done building you must set permissions  so that the docker user www-data can write to the files like so.

`chown -R www-data:www-data /var/www/html/`

After that simple follow the normal Enso install process but inside the 'enso' container

To open a bash shell in the enso container
`docker exec -it enso bash`

### CODE REVIEW

**Comment by aocneanu** [comment]
Of course, this is a great addition.

Could you please make a PR on [docs](https://docs.laravel-enso.com/guide/getting-started.html) and add a `Docker` section ?

Thank you!

**Comment by bytebuddha** [comment]
Yes, though they could stand to be a bit more verbose [here](https://docs.laravel-enso.com/guide/getting-started.html#docker).

**Comment by mauthi** [comment]
Link is not working? I can't find anything about docker there? 

Btw.:
Is there a possibility to make the database persistent and mound the source code from host system?
Sorry for the question, I am not a docker expert so if this is already done ignore it.

**Comment by bytebuddha** [comment]
Hmm thats strange i was been able to see the changes immediately. Here's a link to the pull request https://github.com/laravel-enso/Documentation/pull/19

The source code is mounted into the `/var/www/html/` directory in the enso container automatically.

As for the database it isn't persisted, but changing `- /var/lib/mysql` to 
`- /var/lib/mysql:./$dataDirectory` would do the trick.

**Comment by jlsjonas** [comment]
[**@bytebuddha**](https://github.com/bytebuddha) commented on [May 4, 2019, 4:53 PM GMT+2](https://github.com/laravel-enso/Enso/pull/214#issuecomment-489333924 "2019-05-04T14:53:58Z - Replied by Github Reply Comments"):
> Hmm thats strange i was been able to see the changes immediately. Here's a link to the pull request https://github.com/laravel-enso/Documentation/pull/19


FYI: it's still due to the _rogue_ serviceworker, also see https://github.com/laravel-enso/Documentation/issues/15

**Pull request merged**
