### PR TITLE
Enso RTL support V3

### PR DESCRIPTION
**Pull request by YacoubBelaoura**
# Enso-RTL v3

[edited]
this approach only use css to add RTL support. and `bulma-rtl` package with a patch-file

## Component that got changed

- @enso-ui/ui
- @enso-ui/themes
  > now have + dependency for `bulma-rtl` and it still need a patch that is added to main Enso root dir
  >
  > > it compile now two more styles for `dark-rtl` and `light-rtl`
- @enso-ui/select
- @enso-ui/dropdown
- @enso-ui/transitions
  > now it have a new `HorizontalSlide` that have a `isRTL` prop it combine `slideLeft` & `SlideRight`
- @enso-ui/scroll-to-top

### CODE REVIEW

**Comment by aocneanu** [comment]
I will start reviewing as soon as I have the time. Thank you!

**Comment by jlsjonas** [comment]
General thoughts (I could only have a very quick look so far):

- The `isRTL` tag should be global/injected instead of _polluting_ the props
- Do we really need `vue-styled-components`?

note: these are my thoughts and might not reflect Enso's core team

**Comment by YacoubBelaoura** [comment]
* `isRTL` prop is required outside Enso environment, so other user can still have RTL support for that component. so Global `isRTL` not a good idea.
* and for `vue-styled-components` we can get get rid of it, but the code will not look good, its like what i did in V2. and with the upcoming Vue3 and its new features, this will get us an even cleaner code.

**Comment by jlsjonas** [comment]
>isRTL prop is required outside Enso environment

They can still inject it

>and for `vue-styled-components`

I'll leave that up to @aocneanu

**Comment by YacoubBelaoura** [comment]
sorry about this, but when i was working with tailwindcss i found a new clean way to add rtl-support "that didnt cross my mind" without adding any packages , props or injects.  and i will start working on it ASAP.

hope you didn't review this yet.
and i am really sorry for this.

and @ jlsjonas sorry for not responding, i got really busy, but i found that inject required a lot of change for enso-core to be responsive so i didnt use it.

**Comment by YacoubBelaoura** [comment]
sorry for the delay, 
i updated the PR to use the new approach 
its pro.
 * it only use css to switch rtl & ltr
its con:
 * it still depends on bulma-rtl package with a patch-file
 * still use `isRTL` prop to track and change from rtl to ltr on `dir` attribute for `#App` only for @enso-ui/ui . but not the others.

and thanks in advance.

**Comment by aocneanu** [comment]
This is ready to be merged

**Comment by aocneanu** [comment]
Thank you for you effort & patience :)

**Comment by YacoubBelaoura** [comment]
your welcome :thumbsup:

**Pull request merged**
